name: CI checks

on:
  push:
    branches:
    - main
  pull_request:
    paths-ignore:
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - COPYING
    - NEWS
    - README.md
    - SECURITY.md
    branches:
    - main

jobs:
  check:
    name: Build with gcc and test
    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main' # Needed for updates to work
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          autoconf-archive \
          automake \
          autopoint \
          clang \
          dbus \
          docbook-xml \
          docbook-xsl \
          libglib2.0-dev \
          libtool \
          xsltproc \
          ${NULL+}
    - name: Check out xdg-dbus-proxy
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Create logs dir
      run: mkdir test-logs
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: |
        mkdir _build
        ( cd _build && ../configure --enable-man )
      env:
        CFLAGS: >-
          -O2
          -Wp,-D_FORTIFY_SOURCE=2
          -fsanitize=address
          -fsanitize=undefined
    - name: Build xdg-dbus-proxy
      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) V=1
    - name: Run tests
      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
    - name: Run tests
      run: make -C _build -j $(getconf _NPROCESSORS_ONLN) check VERBOSE=1
    - name: Collect overall test logs on failure
      if: failure()
      run: mv _build/test-suite.log test-logs/ || true
    - name: Collect individual test logs on cancel
      if: failure() || cancelled()
      run: mv _build/tests/*.log test-logs/ || true
    - name: Upload test logs
      uses: actions/upload-artifact@v1
      if: failure() || cancelled()
      with:
        name: test logs
        path: test-logs
    - name: install
      run: |
        make -C _build install DESTDIR="$(pwd)/DESTDIR"
        ( cd DESTDIR && find -ls )
    - name: distcheck
      run: |
        make -C _build -j $(getconf _NPROCESSORS_ONLN) distcheck VERBOSE=1
